version: 1

template:
  title: |
    {{primary_file}} - {{summary}}
  body: |
    ## Summary
    {{description}}

    ## Key Changes
    {{changes}}

style:
  tone: "technical"
  length: "concise"
  include_commits: false
  include_diff: false

naming:
  conventions:
    - "Start with affected command or file (PascalCase for commands)"
    - "Use ` - ` as separator"
    - "Keep concise: describe what the change does"
    - "Examples:"
    - "`Get-DbaDatabase - Add recovery model filtering`"
    - "`dbatools.psm1 - Update initialization logic`"
