## General Settings

## Load environment variables from a specified file (default: .env in git root)
env-file: .aider/.env

## Specify the model to use for chat and code assistance
## Available models: gpt-4o, claude-3-5-sonnet, o1-preview, deepseek, etc.
# model: gpt-4o

## Model for editing code
# editor-model: gpt-4o

## Suggested number of tokens to use for repo map, use 0 to disable (default: 1024)
map-tokens: "0"

## Control how often the repo map is refreshed. Options: auto, always, files, manual (default: auto)
map-refresh: manual

## Enable dark mode for a better terminal appearance on dark backgrounds
dark-mode: true

## Enable pretty, colorized output (default: true)
pretty: true

## Disable streaming responses; waits for full response before displaying
## helps with estimating costs
stream: true

## Enable caching of prompts to reduce token costs (default: false)
cache-prompts: true

## Show the differences between current and previous file versions
show-diffs: false

## Disable automatic commits after changes made by the AI
auto-commits: false

## Prevent the AI from suggesting shell commands during chats
no-suggest-shell-commands: true

## Number of pings to keep the prompt cache alive at 5-minute intervals (default: 0)
cache-keepalive-pings: "5"

## Add aider-specific files to .gitignore (default: true)
gitignore: false

## No reason to lint if ScriptAnalyzer cant fix it
auto-lint: false

## map
show-repo-map: false
#aiderignore: .aider/.aiderignore

## Command to lint PowerShell code using PSScriptAnalyzer
# lint-cmd: pwsh -NoProfile -Command "Invoke-ScriptAnalyzer -Settings /workspace/tests/PSScriptAnalyzerRules.psd1 -Path $@"

## Automatically runs tests after code changes using Pester
auto-test: false

## Command to run PowerShell tests using Pester
#test-cmd: "pwsh -Command Invoke-Pester -Path .\\Tests"

## Control verbosity of the output (default: false)
verbose: false

## Specify the input history file
input-history-file: .aider/aider.input.history

## Specify the chat history file
chat-history-file: .aider/aider.chat.history.md

## Specify the LLM history file
llm-history-file: .aider/aider.llm.history

## Specify model-specific settings
model-settings-file: .aider/aider.model.settings.yml
model-metadata-file: .aider/aider.model.metadata.json

## Completion and Suggestions

## Disable completion suggestions for shell commands
suggest-shell-commands: false

## Git Integration

## Enable Git integration to track file changes
git: false

## Completion Menu Colors

## Set the colors for the completion menu
#completion-menu-color: "cyan"
#completion-menu-bg-color: "black"
#completion-menu-current-color: "white"
#completion-menu-current-bg-color: "blue"

## Miscellaneous Settings

## Code Theme
#code-theme: "monokai"

## edit the whole file
edit-format: diff

## yesss
yes-always: true

show-prompts: false