function Export-DbaDiagnosticQuery {
<#
.SYNOPSIS 
Export-DbaDiagnosticQuery can convert CliXml generated by Invoke-DbaDiagnosticQuery to CSV or Excel

.DESCRIPTION
The default output format of Invoke-DbaDiagnosticQuery is CliXml. It can also output to CSV and Excel. 
However, CSV output can generate a lot of files and Excel output depends on the ImportExcel module by Doug Fike (https://github.com/dfinke/ImportExcel)
Export-DbaDiagnosticQuery can be used to convert from the default export type to the other available export types.

.PARAMETER InputObject
Specifies the objects to convert
	
.PARAMETER ConvertTo
Specifies the output type. Valid choices are Excel and Csv. Csv is the default.
	
.PARAMETER Destination
Specifies the path to the output files. 
	
.PARAMETER NoProgressBar
Do not display a progress bar
	
.PARAMETER Silent
Use this switch to disable any kind of verbose messages

.NOTES
Author: André Kamman (@AndreKamman), http://clouddba.io

dbatools PowerShell module (https://dbatools.io, clemaire@gmail.com)
Copyright (C) 2016 Chrissy LeMaire
This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program.  If not, see <http://www.gnu.org/licenses/>.
You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.	

.LINK
https://dbatools.io/Export-DbaDiagnosticQuery

.EXAMPLE  
Export-DbaDiagnosticQuery -InputObject c:\users\myusername\documents\myfilename.clixml -To Excel -Destination c:\users\myusername\documents\

Converts the specified clixml to possibly multiple Excel sheets
If no Destination is specified, the "My Documents" location will be used

.EXAMPLE  
Export-DbaDiagnosticQuery -InputObject c:\users\myusername\documents\myfilename.clixml -To Csv -Destination c:\temp

Converts the specified clixml to multiple CSV files
#>
	[CmdletBinding()]
	param (
		[parameter(Mandatory = $true, ValueFromPipeline = $true)]
		[object[]]$InputObject,
		[ValidateSet("Excel", "Csv")]
		[string]$ConvertTo = "Csv",
		[System.IO.FileInfo]$Destination = [Environment]::GetFolderPath("mydocuments"),
		[switch]$NoProgressBar,
		[switch]$Silent
	)
	
	begin {
		if ($convertto -eq "Excel") {
			try {
				Import-Module ImportExcel -ErrorAction Stop
			}
			catch {
				Write-Message -Level Output -Message "Failed to load module, exporting to Excel feature is not available"
				Write-Message -Level Output -Message "Install the module from: https://github.com/dfinke/ImportExcel"
				Write-Message -Level Output -Message "Valid alternative conversion format is csv"
				Stop-Function -Message "Exiting"
			}
		}
	}
	
	process {
		if (Test-FunctionInterrupt) { return }
		
		$sqlserver = $InputObject.SqlInstance
		$results = $InputObject.Result
		$resultcounter = 0
		$resulttotal = $results.count
		
		Write-Message -Level Output -Message "Converting $($InputObject.fullname) into $convertto, destination: $Destination"
		
		foreach ($result in $results) {
			$resultcounter += 1
			if (!$NoProgressBar) { Write-Progress -Id 0 -Activity "Exporting clixml resultsets to $convertto" -Status ("Result {0} of {1}" -f $resultcounter, $resulttotal) -CurrentOperation $result.Name -PercentComplete (($resultcounter / $resulttotal) * 100) }
			
			switch ($convertto) {
				"Excel"
				{
					if ($result.dbSpecific) {
						Write-Message -Level Verbose -Message ("Exporting clixml to {0}: {1:00} - {2} for Instance {3} ({4})" -f $convertto, $result.querynr, $result.Name, $sqlserver, $result.DatabaseName)
						$result.result | Export-Excel -Path $Destination\SqlServerDiagnosticQueries_$($sqlserver.Replace("\", "$"))_$($result.DatabaseName).xlsx -WorkSheetname $($result.Name) -AutoSize -AutoFilter -BoldTopRow -FreezeTopRow
					}
					else {
						Write-Message -Level Verbose -Message ("Exporting clixml to {0}: {1:00} - {2} for Instance {3}" -f $convertto, $result.querynr, $result.Name, $sqlserver)
						$result.result | Export-Excel -Path $Destination\SqlServerDiagnosticQueries_$($sqlserver.Replace("\", "$")).xlsx -WorkSheetname $($result.Name) -AutoSize -AutoFilter -BoldTopRow -FreezeTopRow
					}
				}
				"csv"
				{
					if ($result.dbSpecific) {
						Write-Message -Level Verbose -Message ("Exporting clixml to {0}: {1:00} - {2} for Instance {3} ({4})" -f $convertto, $result.querynr, $result.Name, $sqlserver, $result.DatabaseName)
						$result | Export-Csv -Path $Destination\SqlServerDiagnosticQueries_$($sqlserver.Replace("\", "$"))_$($result.DatabaseName)_$($result.QueryNr)_$($result.Name.Replace(" ", "_")).csv -NoTypeInformation
					}
					else {
						Write-Message -Level Verbose -Message ("Exporting clixml to {0}: {1:00} - {2} for Instance {3}" -f $convertto, $result.querynr, $result.Name, $sqlserver)
						$result | Export-Csv -Path $Destination\SqlServerDiagnosticQueries_$($sqlserver.Replace("\", "$"))_$($result.QueryNr)_$($result.Name.Replace(" ", "_")).csv -NoTypeInformation
					}
				}
			}
		}
	}
}
