#
# Module manifest for module 'dbatools'
#
# Generated by: Chrissy LeMaire
#
# Generated on: 9/8/2015
#
@{
    
    # Script module or binary module file associated with this manifest.
    RootModule = 'dbatools.psm1'
    
    # Version number of this module.
    ModuleVersion = '0.8.800'
    
    # ID used to uniquely identify this module
    GUID = '9d139310-ce45-41ce-8e8b-d76335aa1789'
    
    # Author of this module
    Author = 'Chrissy LeMaire'
    
    # Company or vendor of this module
    CompanyName = 'dbatools.io'
    
    # Copyright statement for this module
    Copyright = '2017 Chrissy LeMaire'
    
    # Description of the functionality provided by this module
    Description = 'Provides extra functionality for SQL Server Database admins and enables SQL Server instance migrations.'
    
    # Minimum version of the Windows PowerShell engine required by this module
    PowerShellVersion = '3.0'
    
    # Name of the Windows PowerShell host required by this module
    PowerShellHostName = ''
    
    # Minimum version of the Windows PowerShell host required by this module
    PowerShellHostVersion = ''
    
    # Minimum version of the .NET Framework required by this module
    DotNetFrameworkVersion = ''
    
    # Minimum version of the common language runtime (CLR) required by this module
    CLRVersion = ''
    
    # Processor architecture (None, X86, Amd64, IA64) required by this module
    ProcessorArchitecture = ''
    
    # Modules that must be imported into the global environment prior to importing this module
    RequiredModules = @()
    
    # Assemblies that must be loaded prior to importing this module
    RequiredAssemblies = @()
    
    # Script files () that are run in the caller's environment prior to importing this module
    ScriptsToProcess = @()
    
    # Type files (xml) to be loaded when importing this module
    TypesToProcess = @()
    
    # Format files (xml) to be loaded when importing this module
    FormatsToProcess = @()
    
    # Modules to import as nested modules of the module specified in ModuleToProcess
    NestedModules = @()
    
    # Functions to export from this module
    FunctionsToExport = @(
        'Clear-DbaSqlConnectionPool',
        'Connect-DbaSqlServer',
        'Copy-SqlAgentCategory',
        'Copy-SqlAlert',
        'Copy-SqlAudit',
        'Copy-SqlAuditSpecification',
        'Copy-SqlBackupDevice',
        'Copy-SqlCentralManagementServer',
        'Copy-SqlCredential',
        'Copy-SqlCustomError',
        'Copy-SqlDatabase',
        'Copy-SqlDatabaseAssembly',
        'Copy-SqlDatabaseMail',
        'Copy-SqlDataCollector',
        'Copy-SqlEndpoint',
        'Copy-SqlExtendedEvent',
        'Copy-SqlJob',
        'Copy-SqlLinkedServer',
        'Copy-SqlLogin',
        'Copy-SqlOperator',
        'Copy-SqlPolicyManagement',
        'Copy-SqlProxyAccount',
        'Copy-SqlResourceGovernor',
        'Copy-SqlServerAgent',
        'Copy-SqlServerRole',
        'Copy-SqlServerTrigger',
        'Copy-SqlSharedSchedule',
        'Copy-SqlSpConfigure',
        'Copy-SqlSsisCatalog',
        'Copy-SqlSysDbUserObjects',
        'Expand-SqlTLogResponsibly',
        'Export-DbaAvailabilityGroup',
        'Export-SqlLogin',
        'Export-SqlSpConfigure'
        'Export-SqlUser',
        'Find-DbaAgentJob',
        'Find-DbaDatabase',
        'Find-DbaDependency',
        'Find-DbaLoginInGroup',
        'Find-DbaOrphanedFile',
        'Find-DbaStoredProcedure',
        'Find-DbaUserObject',
        'Find-SqlDuplicateIndex',
        'Find-SqlUnusedIndex',
        'Get-DbaAgentAlert',
        'Get-DbaAgentOperator',
        'Get-DbaAvailabilityGroup',
        'Get-DbaBackupHistory',
        'Get-DbaClusterActiveNode',
        'Get-DbaDatabase',
        'Get-DbaDatabaseFreespace',
        'Get-DbaDatabaseSnapshot',
        'Get-DbaDatabaseState',
        'Get-DbaDetachedDatabaseInfo',
        'Get-DbaDiskSpace',
        'Get-DbaHelpIndex',
        'Get-DbaLastBackup',
        'Get-DbaLastGoodCheckDb',
        'Get-DbaMaxMemory',
        'Get-DbaMemoryUsage',
        'Get-DbaMemoryUsage',
        'Get-DbaMsdtc',
        'Get-DbaPageFileSetting',
        'Get-DbaPermission',
        'Get-DbaProcess',
        'Get-DbaRestoreHistory',
        'Get-DbaRoleMember',
        'Get-DbaRunningJob',
        'Get-DbaSpConfigure',
        'Get-DbaSpn',
        'Get-DbaSqlService',
        'Get-DbaStartupParameter',
        'Get-DbaTcpPort',
        'Get-DbaTrigger',
        'Get-DbaUptime',
        'Get-DbaXEventsSession',
        'Get-SqlRegisteredServerName',
        'Get-SqlServerKey',
        'Import-CsvToSql',
        'Import-SqlSpConfigure',
        'Install-SqlWhoIsActive',
        'Measure-DbaBackupThroughput',
        'Move-DbaDatabaseFile',
        'New-DbaDatabaseSnapshot',
        'Out-DbaDataTable',
        'Read-DbaBackupHeader',
        'Remove-DbaBackup',
        'Remove-DbaDatabaseSnapshot',
        'Remove-DbaSpn',
        'Remove-SqlDatabaseSafely',
        'Remove-SqlOrphanUser',
        'Rename-DbaLogin',
        'Repair-DbaServerName',
        'Repair-SqlOrphanUser',
        'Reset-SqlAdmin',
        'Resolve-DbaNetworkName',
        'Restore-DbaBackup',
        'Restore-DbaDatabase',
        'Restore-DbaFromDatabaseSnapshot',
        'Restore-SqlBackupFromDirectory',
        'Set-DbaDatabaseOwner',
        'Set-DbaDatabaseState',
        'Set-DbaJobOwner',
        'Set-DbaMaxDop',
        'Set-DbaMaxMemory',
        'Set-DbaPowerPlan',
        'Set-DbaSpn',
        'Set-SqlTempDbConfiguration',
        'Show-SqlDatabaseList',
        'Show-SqlServerFileSystem',
        'Show-SqlWhoIsActive',
        'Start-SqlMigration',
        'Stop-DbaProcess',
        'Sync-SqlLoginPermissions',
        'Test-DbaConnectionAuthScheme',
        'Test-DbaDatabaseCollation',
        'Test-DbaDatabaseCompatibility',
        'Test-DbaDatabaseOwner',
        'Test-DbaDiskAlignment',
        'Test-DbaDiskAllocation',
        'Test-DbaFullRecoveryModel',
        'Test-DbaJobOwner',
        'Test-DbaLastBackup',
        'Test-DbaMaxDop',
        'Test-DbaMaxMemory',
        'Test-DbaOptimizeForAdHoc',
        'Test-DbaPowerPlan',
        'Test-DbaServerName',
        'Test-DbaSpn',
        'Test-DbaValidLogin',
        'Test-DbaVirtualLogFile',
        'Test-SqlConnection',
        'Test-SqlMigrationConstraint',
        'Test-SqlNetworkLatency',
        'Test-SqlPath',
        'Test-SqlTempDbConfiguration',
        'Update-dbatools',
        'Update-SqlWhoIsActive',
        'Watch-SqlDbLogin',
        'Write-DbaDataTable'
    )
    
	<# coming soon
	
		'Get-DbaLinkedServer'
	#>
    
    # Cmdlets to export from this module
    CmdletsToExport = '*'
    
    # Variables to export from this module
    VariablesToExport = '*'
    
    # Aliases to export from this module
    # Aliases are stored in dbatools.psm1
    AliasesToExport = @(
        'Copy-SqlJobServer',
        'Copy-SqlUserDefinedMessage',
        'Get-DiskSpace',
        'Get-SqlMaxMemory',
        'Reset-SqlSaPassword',
        'Restore-HallengrenBackup',
        'Set-SqlMaxMemory',
        'Show-SqlMigrationConstraint',
        'Test-SqlDiskAllocation',
        'Update-SqlWhoIsActive'
    )
    
    # List of all modules packaged with this module
    ModuleList = @()
    
    # List of all files packaged with this module
    FileList = ''
    
    PrivateData = @{
        # PSData is module packaging and gallery metadata embedded in PrivateData
        # It's for rebuilding PowerShellGet (and PoshCode) NuGet-style packages
        # We had to do this because it's the only place we're allowed to extend the manifest
        # https://connect.microsoft.com/PowerShell/feedback/details/421837
        PSData = @{
            # The primary categorization of this module (from the TechNet Gallery tech tree).
            Category = "Databases"
            
            # Keyword tags to help users find this module via navigations and search.
            Tags = @('sqlserver', 'migrations', 'sql', 'dba', 'databases')
            
            # The web address of an icon which can be used in galleries to represent this module
            IconUri = "https://dbatools.io/logo.png"
            
            # The web address of this module's project or support homepage.
            ProjectUri = "https://dbatools.io"
            
            # The web address of this module's license. Points to a page that's embeddable and linkable.
            LicenseUri = "http://www.gnu.org/licenses/gpl-3.0.en.html"
            
            # Release notes for this particular version of the module
            ReleaseNotes = "https://dbatools.io/releases"
            
            # If true, the LicenseUrl points to an end-user license (not just a source license) which requires the user agreement before use.
            # RequireLicenseAcceptance = ""
            
            # Indicates this is a pre-release/testing version of the module.
            IsPrerelease = 'True'
        }
    }
}