#
# Module manifest for module 'dbatools'
#
# Generated by: Chrissy LeMaire
#
# Generated on: 9/8/2015
#
@{

    # Script module or binary module file associated with this manifest.
    RootModule         = 'dbatools.psm1'

    # Version number of this module.
    ModuleVersion      = '2.8.2'

    # ID used to uniquely identify this module
    GUID               = '9d139310-ce45-41ce-8e8b-d76335aa1789'

    # Author of this module
    Author             = 'the dbatools team'

    # Company or vendor of this module
    CompanyName        = 'dbatools.io'

    # Copyright statement for this module
    Copyright          = 'Copyright (c) 2025 by dbatools, licensed under MIT'

    # Description of the functionality provided by this module
    Description        = "The community module that enables SQL Server Pros to automate database development and server administration"

    # Modules that must be imported into the global environment prior to importing this module
    RequiredModules    = @(
        @{
        ModuleName    = 'dbatools.library';
        ModuleVersion = '2025.12.28'
    },
        'dbatools.core',
        'dbatools.agent',
        'dbatools.hadr',
        'dbatools.security',
        'dbatools.database',
        'dbatools.performance',
        'dbatools.xevents',
        'dbatools.maintenance',
        'dbatools.computer',
        'dbatools.replication',
        'dbatools.ssis'
    )

    # Assemblies that must be loaded prior to importing this module
    RequiredAssemblies = @()

    # Script files () that are run in the caller's environment prior to importing this module
    ScriptsToProcess   = @()

    # Type files (xml) to be loaded when importing this module
    TypesToProcess     = @("xml\dbatools.Types.ps1xml")

    # Format files (xml) to be loaded when importing this module
    # "xml\dbatools.Format.ps1xml"
    FormatsToProcess   = @("xml\dbatools.Format.ps1xml")

    # Modules to import as nested modules of the module specified in ModuleToProcess
    NestedModules      = @()

    # Functions to export from this module
    # Specific functions to export for Core, etc are also found in psm1
    # FunctionsToExport specifically helps with AUTO-LOADING so do not remove
    FunctionsToExport  = @(
        'Test-DbaAgSpn',
        'Add-DbaAgDatabase',
        'Add-DbaAgListener',
        'Add-DbaAgReplica',
        'Add-DbaDbMirrorMonitor',
        'Backup-DbaDatabase',
        'Test-DbaBackupEncrypted',
        'Compare-DbaAgReplicaLogin',
        'Compare-DbaAgReplicaOperator',
        'Compare-DbaAgReplicaSync',
        'Compare-DbaAvailabilityGroup',
        'Copy-DbaBackupDevice',
        'Copy-DbaCredential',
        'Copy-DbaCustomError',
        'Copy-DbaDatabase',
        'Copy-DbaDataCollector',
        'Copy-DbaDbAssembly',
        'Copy-DbaDbMail',
        'Copy-DbaDbQueryStoreOption',
        'Copy-DbaDbTableData',
        'Copy-DbaDbViewData',
        'Copy-DbaEndpoint',
        'Copy-DbaExtendedStoredProcedure',
        'Copy-DbaInstanceAudit',
        'Copy-DbaInstanceAuditSpecification',
        'Copy-DbaInstanceTrigger',
        'Copy-DbaLinkedServer',
        'Copy-DbaLogin',
        'Copy-DbaPolicyManagement',
        'Copy-DbaResourceGovernor',
        'Copy-DbaServerRole',
        'Copy-DbaSpConfigure',
        'Copy-DbaStartupProcedure',
        'Copy-DbaSystemDbUserObject',
        'Disable-DbaAgHadr',
        'Disable-DbaFilestream',
        'Disable-DbaHideInstance',
        'Disable-DbaStartupProcedure',
        'Disable-DbaTraceFlag',
        'Enable-DbaAgHadr',
        'Enable-DbaFilestream',
        'Enable-DbaHideInstance',
        'Enable-DbaStartupProcedure',
        'Enable-DbaTraceFlag',
        'Export-DbaCredential',
        'Export-DbaDiagnosticQuery',
        'Export-DbaInstance',
        'Export-DbaLinkedServer',
        'Export-DbaRegServer',
        'Export-DbaReplServerSetting',
        'Export-DbaSpConfigure',
        'Find-DbaBackup',
        'Find-DbaCommand',
        'Get-DbaAgBackupHistory',
        'Get-DbaAgDatabase',
        'Get-DbaAgDatabaseReplicaState',
        'Get-DbaAgHadr',
        'Get-DbaBackupDevice',
        'Get-DbaCmConnection',
        'Get-DbaCmObject',
        'Get-DbaCredential',
        'Get-DbaDatabase',
        'Get-DbaDbBackupHistory',
        'Get-DbaDbccHelp',
        'Get-DbaDbccStatistic',
        'Remove-DbaDbCheckConstraint',
        'Get-DbaDbEncryption',
        'New-DbaDbEncryptionKey',
        'Remove-DbaDbPartitionScheme',
        'Remove-DbaDbPartitionFunction',
        'Get-DbaDbRecoveryModel',
        'Get-DbaDbRestoreHistory',
        'Remove-DbaDbTable',
        'Get-DbaErrorLogConfig',
        'Get-DbaExtendedProtection',
        'Get-DbaFilestream',
        'Get-DbaHideInstance',
        'Get-DbaInstanceAudit',
        'Get-DbaInstanceAuditSpecification',
        'Get-DbaInstanceInstallDate',
        'Get-DbaInstanceProtocol',
        'Get-DbaInstanceTrigger',
        'Get-DbaInstanceUserOption',
        'Get-DbaLastBackup',
        'Get-DbaLastGoodCheckDb',
        'Get-DbaLinkedServer',
        'Get-DbaLogin',
        'Get-DbaMaintenanceSolutionLog',
        'Get-DbaPbmCategorySubscription',
        'Get-DbaPbmCondition',
        'Get-DbaPbmStore',
        'Get-DbaPermission',
        'Get-DbaProcess',
        'Get-DbaRegServer',
        'Get-DbaRegServerGroup',
        'Get-DbaRegServerStore',
        'Get-DbaReplPublication',
        'Get-DbaReplServer',
        'Get-DbaServerRole',
        'Get-DbaServerRoleMember',
        'Get-DbaSpConfigure',
        'Copy-DbaSsisCatalog',
        'Get-DbaSsisEnvironmentVariable',
        'New-DbaSsisCatalog',
        'Get-DbaStartupProcedure',
        'Get-DbaTcpPort',
        'Get-DbaUserPermission',
        'Get-DbaXEObject',
        'Get-DbaXESession',
        'Get-DbaXESessionTarget',
        'Get-DbaXESessionTargetFile',
        'Get-DbaXESessionTemplate',
        'Get-DbaXEStore',
        'Import-DbaRegServer',
        'Import-DbaSpConfigure',
        'Install-DbaDarlingData',
        'Install-DbaFirstResponderKit',
        'Install-DbaMaintenanceSolution',
        'Install-DbaMultiTool',
        'Install-DbaSqlPackage',
        'Install-DbaSqlWatch',
        'Install-DbaWhoIsActive',
        'Invoke-DbaDbAzSqlTip',
        'Invoke-DbaCycleErrorLog',
        'Invoke-DbaDbccDropCleanBuffer',
        'Invoke-DbaDbccFreeCache',
        'Invoke-DbaDbDataMasking',
        'Invoke-DbaDbDbccCheckConstraint',
        'Invoke-DbaDbDbccCleanTable',
        'Invoke-DbaDbDbccUpdateUsage',
        'Invoke-DbaDbLogShipRecovery',
        'Invoke-DbaDbMirrorFailover',
        'Invoke-DbaDbMirroring',
        'Invoke-DbaDbPiiScan',
        'Invoke-DbaDbShrink',
        'Invoke-DbaDbTransfer',
        'Invoke-DbaDbUpgrade',
        'Invoke-DbaWhoIsActive',
        'Join-DbaAvailabilityGroup',
        'Measure-DbaDiskSpaceRequirement',
        'Mount-DbaDatabase',
        'Move-DbaDbFile',
        'New-DbaAgentOperator',
        'New-DbaAgentProxy',
        'New-DbaAgentSchedule',
        'New-DbaAvailabilityGroup',
        'New-DbaDacOption',
        'New-DbaDacPackage',
        'New-DbaDacProfile',
        'New-DbaDatabase',
        'New-DbaDbAsymmetricKey',
        'New-DbaDbCertificate',
        'New-DbaDbDataGeneratorConfig',
        'New-DbaDbFileGroup',
        'New-DbaDbMailAccount',
        'New-DbaDbMailProfile',
        'New-DbaDbMaskingConfig',
        'New-DbaDbMasterKey',
        'New-DbaDbRole',
        'New-DbaDbSchema',
        'New-DbaDbSequence',
        'New-DbaDbSnapshot',
        'New-DbaDbSynonym',
        'New-DbaDbTable',
        'New-DbaDbTransfer',
        'New-DbaDbUser',
        'New-DbaDirectory',
        'New-DbaEndpoint',
        'New-DbaLogin',
        'New-DbaServerRole',
        'New-DbaXESession',
        'Publish-DbaDacPackage',
        'Read-DbaTransactionLog',
        'Remove-DbaAgDatabase',
        'Remove-DbaAgentJob',
        'Remove-DbaAgentJobSchedule',
        'Remove-DbaAgentJobStep',
        'Remove-DbaAgListener',
        'Remove-DbaAgReplica',
        'Remove-DbaAvailabilityGroup',
        'Remove-DbaDatabaseSafely',
        'Remove-DbaDbData',
        'Remove-DbaDbFileGroup',
        'Remove-DbaDbLogShipping',
        'Remove-DbaDbMirror',
        'Remove-DbaDbMirrorMonitor',
        'Remove-DbaDbOrphanUser',
        'Remove-DbaDbRole',
        'Remove-DbaDbRoleMember',
        'Remove-DbaDbSchema',
        'Remove-DbaDbSequence',
        'Remove-DbaDbSnapshot',
        'Remove-DbaDbSynonym',
        'Remove-DbaDbTableData',
        'Remove-DbaDbUser',
        'Remove-DbaDbView',
        'Remove-DbaEndpoint',
        'Remove-DbaXESession',
        'Repair-DbaDbMirror',
        'Repair-DbaDbOrphanUser',
        'Restore-DbaDbSnapshot',
        'Resume-DbaAgDbDataMovement',
        'Revoke-DbaAgPermission',
        'Select-DbaDbSequenceNextValue',
        'Set-DbaAgentAlert',
        'Set-DbaAgentJob',
        'Set-DbaAgentJobCategory',
        'Set-DbaAgentJobOutputFile',
        'Set-DbaAgentJobStep',
        'Set-DbaAgentSchedule',
        'Set-DbaAgentServer',
        'Set-DbaAgListener',
        'Set-DbaAgReplica',
        'Set-DbaAvailabilityGroup',
        'Set-DbaDbCompatibility',
        'Set-DbaDbCompression',
        'Set-DbaDbFileGroup',
        'Set-DbaDbIdentity',
        'Set-DbaDbMailAccount',
        'Set-DbaDbMirror',
        'Set-DbaDbQueryStoreOption',
        'Set-DbaDbSchema',
        'Set-DbaDbSequence',
        'Set-DbaEndpoint',
        'Set-DbaNetworkCertificate',
        'Start-DbaAgentJob',
        'Start-DbaEndpoint',
        'Start-DbaMigration',
        'Stop-DbaEndpoint',
        'Stop-DbaXESession',
        'Suspend-DbaAgDbDataMovement',
        'Sync-DbaAvailabilityGroup',
        'Test-DbaAgentJobOwner',
        'Test-DbaAgPolicyState',
        'Test-DbaAvailabilityGroup',
        'Test-DbaDbDataGeneratorConfig',
        'Test-DbaDbDataMaskingConfig',
        'Test-DbaDbLogShipStatus',
        'Test-DbaDbQueryStore',
        'Test-DbaEndpoint',
        'Test-DbaIdentityUsage',
        'Test-DbaMigrationConstraint',
        'Test-DbaReplLatency',
        'Uninstall-DbaSqlWatch',
        'Set-DbaAgentOperator',
        'Remove-DbaExtendedProperty',
        'Set-DbaExtendedProperty',
        'Set-DbaDbDataClassification',
        'Remove-DbaDbDataClassification',
        'Remove-DbaDbUdf',
        'Save-DbaCommunitySoftware',
        'Update-DbaMaintenanceSolution',
        'Get-DbaLinkedServerLogin',

        # NEW REPLICATION STUFF
        'Disable-DbaReplDistributor',
        'Enable-DbaReplDistributor',
        'Disable-DbaReplPublishing',
        'Enable-DbaReplPublishing',
        'New-DbaReplPublication',
        'Get-DbaReplArticle',
        'Get-DbaReplArticleColumn',
        'Add-DbaReplArticle',
        'Remove-DbaReplArticle',
        'Remove-DbaReplPublication',
        'New-DbaReplSubscription',
        'Remove-DbaReplSubscription',
        'New-DbaReplCreationScriptOptions',
        'Get-DbaReplSubscription',
        'Get-DbaInstanceList'
    )

    # Cmdlets to export from this module
    CmdletsToExport    = @(
        'Select-DbaObject',
        'Set-DbatoolsConfig'
    )

    # Variables to export from this module
    VariablesToExport  = ''

    # Aliases to export from this module
    # Aliases are stored in dbatools.psm1
    # The five listed below are intentional
    AliasesToExport    = @(
        'Get-DbaRegisteredServer',
        'Attach-DbaDatabase',
        'Detach-DbaDatabase',
        'Start-SqlMigration',
        'Write-DbaDataTable',
        'Get-DbaDbModule',
        'Get-DbaBuildReference',
        'Copy-DbaSysDbUserObject',

        # replication aliases - these existed before the repl overhaul in 2.0+
        'Get-DbaRepServer',
        'Export-DbaRepServerSetting',
        'Get-DbaRepDistributor',
        'Test-DbaRepLatency',
        'Get-DbaRepDistributor',
        'Get-DbaRepPublication',
        'Get-DbaRepServer'

    )


    # List of all modules packaged with this module
    ModuleList         = @()

    # List of all files packaged with this module
    FileList           = ''

    PrivateData        = @{
        # PSData is module packaging and gallery metadata embedded in PrivateData
        # It's for rebuilding PowerShellGet (and PoshCode) NuGet-style packages
        # We had to do this because it's the only place we're allowed to extend the manifest
        # https://connect.microsoft.com/PowerShell/feedback/details/421837
        PSData = @{
            # The primary categorization of this module (from the TechNet Gallery tech tree).
            Category     = "Databases"

            # Keyword tags to help users find this module via navigations and search.
            Tags         = @('sqlserver', 'migrations', 'sql', 'dba', 'databases', 'mac', 'linux', 'core')

            # The web address of an icon which can be used in galleries to represent this module
            IconUri      = "https://dbatools.io/logo.png"

            # The web address of this module's project or support homepage.
            ProjectUri   = "https://dbatools.io"

            # The web address of this module's license. Points to a page that's embeddable and linkable.
            LicenseUri   = "https://opensource.org/licenses/MIT"

            # Release notes for this particular version of the module
            ReleaseNotes = "https://dbatools.io/changelog"

            # If true, the LicenseUrl points to an end-user license (not just a source license) which requires the user agreement before use.
            # RequireLicenseAcceptance = ""

            # Indicates this is a pre-release/testing version of the module.
        }
    }
}
