#Requires -Module @{ ModuleName="Pester"; ModuleVersion="5.0" }
param(
    $ModuleName = "dbatools"
)

# quit failing appveyor
if ($env:appveyor) {
    $names = @(
        "Microsoft.SqlServer.Management.XEvent",
        "Microsoft.SqlServer.Management.XEventDbScoped",
        "Microsoft.SqlServer.Management.XEventDbScopedEnum",
        "Microsoft.SqlServer.Management.XEventEnum",
        "Microsoft.SqlServer.Replication",
        "Microsoft.SqlServer.Rmo"
    )

    foreach ($name in $names) {
        $library = Split-Path -Path (Get-Module dbatools*library).Path
        $path = Join-DbaPath -Path $library -ChildPath desktop
        $path = Join-DbaPath -Path $path -ChildPath lib
        Add-Type -Path (Join-Path -path $path -ChildPath "$name.dll")
    }
}

if ($SkipHelpTest) { return }

## When testing help, remember that help is cached at the beginning of each session.
## To test, restart session.

Describe "dbatools Module Help" -Tag Help {
    <#
    Every command is checked in one pass and the findings are collected per rule, so a failure names
    every command it applies to rather than producing one test result per command and per rule. The
    per-command form is around 27000 test results.

    This file used to wrap the whole thing in "foreach ($command in $global:commandsWithHelp)" at the
    top level of the Describe. That loop runs while Pester discovers the tests, and the BeforeAll
    that filled $global:commandsWithHelp runs long afterwards - so the loop found nothing and the
    file produced zero tests. It had been that way for years.
    #>
    BeforeAll {
        . "$PSScriptRoot\InModule.Help.Exceptions.ps1"

        $includedNames = (Get-ChildItem "$PSScriptRoot\..\public" | Where-Object Name -like "*.ps1").BaseName
        $commandsWithHelp = Get-Command -Module (Get-Module $ModuleName) -CommandType Cmdlet, Function |
            Where-Object { $PSItem.Name -in $includedNames -and $PSItem.Name -notin $global:FunctionHelpTestExceptions } |
            Sort-Object -Property Name

        # The common parameters have to come from PowerShell and not from a hard coded list. The list
        # this file carried was the Windows PowerShell 5.1 set, so on PowerShell 7.4 and later every
        # command was measured against a ProgressAction parameter that comment based help never
        # documents - 2151 failures that say nothing about the help. This property is edition
        # correct: it contains ProgressAction on 7.4 and later and leaves it out on 5.1.
        # WhatIf and Confirm are deliberately not excluded. They are OptionalCommonParameters, but
        # 368 commands document them and only three do not, so they are held to the same standard.
        $commonParameterName = [System.Management.Automation.PSCmdlet]::CommonParameters

        $autoGeneratedSynopsis = @()
        $missingDescription = @()
        $missingExampleCode = @()
        $missingExampleRemarks = @()
        $missingNavigationLink = @()
        $wrongOnlineLink = @()
        $extraParameterInHelp = @()
        $missingParameterDescription = @()
        $wrongRequiredValue = @()
        $wrongParameterType = @()

        foreach ($command in $commandsWithHelp) {
            $commandName = $command.Name
            $commandHelp = Get-Help $commandName -ErrorAction SilentlyContinue

            # If help is not found, the synopsis of the auto-generated help is the syntax diagram.
            # This is a regex and not -BeLike on purpose: in a wildcard pattern the brackets are a
            # character class, so the escaped form this file used matched any synopsis containing
            # one of those letters - which is nearly all of them.
            if ($commandHelp.Synopsis -match "\[<CommonParameters>\]") {
                $autoGeneratedSynopsis += $commandName
            }

            if (-not $commandHelp.Description.Text) {
                $missingDescription += $commandName
            }

            $firstExample = $commandHelp.Examples.Example | Select-Object -First 1
            if (-not $firstExample.Code) {
                $missingExampleCode += $commandName
            }
            if (-not ($firstExample.Remarks | Select-Object -First 1).Text) {
                $missingExampleRemarks += $commandName
            }

            $navigationLink = @($commandHelp.relatedLinks.NavigationLink)
            if (-not $navigationLink) {
                $missingNavigationLink += $commandName
            } elseif ($navigationLink[0].uri -ne "https://dbatools.io/$commandName") {
                $wrongOnlineLink += "$commandName has [$($navigationLink[0].uri)]"
            }

            $commandParameter = $command.ParameterSets.Parameters |
                Sort-Object -Property Name -Unique |
                Where-Object Name -notin $commonParameterName
            $helpParameterName = $commandHelp.Parameters.Parameter.Name | Sort-Object -Unique

            foreach ($extraParameter in $helpParameterName | Where-Object { $PSItem -notin $commandParameter.Name }) {
                $extraParameterInHelp += "$commandName -$extraParameter"
            }

            foreach ($parameter in $commandParameter) {
                $parameterName = $parameter.Name
                $parameterHelp = $commandHelp.parameters.parameter | Where-Object Name -eq $parameterName

                if (-not $parameterHelp.Description.Text) {
                    $missingParameterDescription += "$commandName -$parameterName"
                }

                # Required value in help should match the IsMandatory property of the parameter
                $codeMandatory = $parameter.IsMandatory.ToString()
                if ($parameterHelp.Required -ne $codeMandatory) {
                    $wrongRequiredValue += "$commandName -$parameterName says $($parameterHelp.Required), code says $codeMandatory"
                }

                if ($global:HelpTestSkipParameterType[$commandName] -contains $parameterName) {
                    continue
                }

                # Parameter type in help should match the code
                $codeType = $parameter.ParameterType.Name
                if ($parameter.ParameterType.IsEnum) {
                    # Enumerations often have issues with the typename not being reliably available
                    $enumName = $parameter.ParameterType::GetNames($parameter.ParameterType)
                    if (Compare-Object -ReferenceObject @($enumName) -DifferenceObject @($parameterHelp.parameterValueGroup.parameterValue)) {
                        $wrongParameterType += "$commandName -$parameterName does not list the values of $codeType"
                    }
                } elseif ($parameter.ParameterType.FullName -in $global:HelpTestEnumeratedArrays) {
                    # Enumerations often have issues with the typename not being reliably available
                    $enumName = [Enum]::GetNames($parameter.ParameterType.DeclaredMembers[0].ReturnType)
                    if (Compare-Object -ReferenceObject @($enumName) -DifferenceObject @($parameterHelp.parameterValueGroup.parameterValue)) {
                        $wrongParameterType += "$commandName -$parameterName does not list the values of $codeType"
                    }
                } else {
                    # To avoid calling Trim method on a null object.
                    $helpType = if ($parameterHelp.parameterValue) { $parameterHelp.parameterValue.Trim() }
                    if ($helpType -ne $codeType) {
                        $wrongParameterType += "$commandName -$parameterName says $helpType, code says $codeType"
                    }
                }
            }
        }
    }

    It "checks the help of every public command" {
        # Without this the whole Describe passes when the command list is empty, which is exactly the
        # failure this file had for years.
        $commandsWithHelp | Should -Not -BeNullOrEmpty
    }

    It "has no auto-generated help" {
        $autoGeneratedSynopsis | Should -BeNullOrEmpty -Because "a synopsis that is the syntax diagram means there is no comment based help at all"
    }

    It "has a description for every command" {
        $missingDescription | Should -BeNullOrEmpty
    }

    It "has at least one example with code for every command" {
        $missingExampleCode | Should -BeNullOrEmpty
    }

    It "has at least one example with remarks for every command" {
        $missingExampleRemarks | Should -BeNullOrEmpty -Because "the description of an example needs a blank line above it, otherwise it becomes part of the code"
    }

    It "has a related navigation link for every command" {
        $missingNavigationLink | Should -BeNullOrEmpty -Because "We need a .LINK for Get-Help -Online to work"
    }

    It "has the correct online link for every command" {
        $wrongOnlineLink | Should -BeNullOrEmpty -Because "The web-page should be the one for the command, and a second url needs its own .LINK"
    }

    It "has no parameter in help that the command does not have" {
        $extraParameterInHelp | Should -BeNullOrEmpty
    }

    It "has a description for every parameter" {
        $missingParameterDescription | Should -BeNullOrEmpty
    }

    It "has the correct Required value for every parameter" {
        $wrongRequiredValue | Should -BeNullOrEmpty
    }

    It "has the correct type for every parameter" {
        $wrongParameterType | Should -BeNullOrEmpty
    }
}
