name: Bug Report
description: File a bug report
labels: ["bugs life", "triage required"]
body:
  - type: markdown
    id: intro-md
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! dbatools is testing out a beta of the [new Issues Forms](https://github.blog/changelog/2021-06-23-whats-new-with-github-issues/).
        Please ensure you provide as much information as asked to better assist in confirming and identifying a fix for the bug report.
  - type: dropdown
    id: existing-issue
    attributes:
      label: "Verified issue does not already exist?"
      description: "Please search to see if an issue already exists for the bug you encountered."
      options:
        - "Yes"
        - "No"
    validations:
      required: true
  - type: textarea
    id: errors-received
    attributes:
      label: "What error did you receive?"
      description: "Please provide the full error object that can be found after reproducing the error/issue. You can copy/paste the output from: $error[0] | select *"
    validations:
      required: true
  - type: textarea
    id: command-run
    attributes:
      label: "Steps to Reproduce"
      description: "Command(s) and or steps to reproduce the reported error."
      value: |
        ```powershell
        # provide your command(s) executed pertaining to dbatools
        # please include variable values (redacted or fake if needed) for reference
        ```
    validations:
      required: true
  - type: dropdown
    id: latest
    attributes:
      label: "Are you running the latest release?"
      description: "Please ensure the bug/error can be reproduced in the latest release of the module"
      options:
        - "Yes"
    validations:
      required: false
  - type: textarea
    id: other
    attributes:
      label: "Other details or mentions"
      description: "Please provide any other details or worthy mentions around this issue report"
    validations:
      required: false
  - type: markdown
    id: env-info
    attributes:
      value: "## Environment Details"
  - type: dropdown
    id: host-detail
    attributes:
      label: "What PowerShell host was used when producing this error"
      multiple: true
      options:
        - PowerShell Core (pwsh.exe)
        - Windows PowerShell (powershell.exe)
        - Windows PowerShell ISE (powershell_ise.exe)
        - VS Code (terminal)
        - VS Code (integrated terminal)
    validations:
      required: true
  - type: textarea
    id: ps-version
    attributes:
      label: "PowerShell Host Version"
      description: "You can provide the output from: $PSVersionTable | Set-Clipboard"
    validations:
      required: true
  - type: textarea
    id: sql-version
    attributes:
      label: "SQL Server Edition and Build number"
      description: "You can provide the output from: SELECT @@VERSION"
    validations:
      required: true
  - type: textarea
    id: net-version
    attributes:
      label: ".NET Framework Version"
      description: "Note as of 1.1.0 release our model requires .NET Framework 4.6.2 to be present on Windows devices. You can paste the output from: [System.Runtime.InteropServices.RuntimeInformation]::get_FrameworkDescription() | Set-Clipboard"
    validations:
      required: true
