function Get-DbaXESessionTargetFile {
    <#
    .SYNOPSIS
        Retrieves physical Extended Events target files from the file system for analysis and troubleshooting.

    .DESCRIPTION
        Returns file system objects for Extended Events session target files, allowing you to examine the actual XE log files created by file-based targets. This function locates and lists the physical .xel files generated by Extended Events sessions, making it easy to access them for analysis with tools like SQL Server Management Studio or third-party XE file readers. Handles both local and remote SQL Server instances, automatically resolving UNC paths for remote servers so you can access XE files regardless of where the SQL Server is located.

    .PARAMETER SqlInstance
        The target SQL Server

    .PARAMETER SqlCredential
        Login to the target instance using alternative credentials. Accepts PowerShell credentials (Get-Credential).

        Windows Authentication, SQL Server Authentication, Active Directory - Password, and Active Directory - Integrated are all supported.

        For MFA support, please use Connect-DbaInstance.

    .PARAMETER Session
        Specifies the Extended Events session name to retrieve target files from. Filters results to only include files generated by the specified session.
        Use this when you want to focus on files from a specific XE session like 'system_health' or custom monitoring sessions rather than all sessions on the instance.

    .PARAMETER Target
        Specifies the Extended Events target name to retrieve files from within the specified session. Filters results to only include files from the specified target.
        Use this when a session has multiple targets and you only need files from specific targets like 'event_file' or custom target configurations.

    .PARAMETER InputObject
        Accepts Extended Events target objects piped from Get-DbaXESessionTarget for processing their associated target files.
        Use this when you want to chain commands to first get specific targets and then retrieve their corresponding physical files on the file system.

    .PARAMETER EnableException
        By default, when something goes wrong we try to catch it, interpret it and give you a friendly warning message.
        This avoids overwhelming you with "sea of red" exceptions, but is inconvenient because it basically disables advanced scripting.
        Using this switch turns this "nice by default" feature off and enables you to catch exceptions with your own try/catch.

    .NOTES
        Tags: ExtendedEvent, XE, XEvent
        Author: Chrissy LeMaire (@cl), netnerds.net

        Website: https://dbatools.io
        Copyright: (c) 2018 by dbatools, licensed under MIT
        License: MIT https://opensource.org/licenses/MIT

    .LINK
        https://dbatools.io/Get-DbaXESessionTargetFile

    .EXAMPLE
        PS C:\> Get-DbaXESessionTargetFile -SqlInstance sql2017 -Session 'Long Running Queries'

        Shows Target Files for the 'Long Running Queries' session on sql2017.

    .EXAMPLE
        PS C:\> Get-DbaXESession -SqlInstance sql2016 -Session 'Long Running Queries' | Get-DbaXESessionTarget | Get-DbaXESessionTargetFile

        Returns the Target Files for the system_health session on sql2016.

    #>
    [CmdletBinding(DefaultParameterSetName = "Default")]
    param (
        [parameter(ValueFromPipeline, ParameterSetName = "instance", Mandatory)]
        [DbaInstanceParameter[]]$SqlInstance,
        [PSCredential]$SqlCredential,
        [string[]]$Session,
        [string[]]$Target,
        [parameter(ValueFromPipeline, ParameterSetName = "piped", Mandatory)]
        [Microsoft.SqlServer.Management.XEvent.Target[]]$InputObject,
        [switch]$EnableException
    )

    process {
        if (Test-FunctionInterrupt) { return }

        foreach ($instance in $SqlInstance) {
            $InputObject += Get-DbaXESessionTarget -SqlInstance $instance -SqlCredential $SqlCredential -Session $Session -Target $Target | Where-Object File -ne $null
        }

        foreach ($object in $InputObject) {
            $computer = [dbainstance]$object.ComputerName
            try {
                if ($computer.IsLocal) {
                    $file = $object.TargetFile
                    Write-Message -Level Verbose -Message "Getting $file"
                    Get-ChildItem "$file*" -ErrorAction Stop
                } else {
                    $file = $object.RemoteTargetFile
                    Write-Message -Level Verbose -Message "Getting $file"
                    Get-ChildItem -Recurse "$file*" -ErrorAction Stop
                }
            } catch {
                Stop-Function -Message "Failure" -ErrorRecord $_
            }
        }
    }
}