name: Mark stale issues

on:
  workflow_dispatch:

permissions:
  issues: write

jobs:
  stale:

    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - uses: actions/stale@eb5cf3af3ac0a1aa4c9c45633dd1ae542a27a899 # v10.3.0
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: >
          🚧🚨
          This issue is being marked as stale due to 90 days of inactivity.
          If you would like this issue to remain open:
            * Verify the issue/bug is reproduced in the latest version of the module
            * Verify the environmental info provided is still accurate
            * Add any additional steps you followed to reproduce if necessary
          🚨🚧
          
          ⌛️ Stale issues are reviewed periodically by the maintainers ⌛️
        stale-issue-label: stale
        exempt-issue-labels: 'Feature,Documentation,Question,Confirmed,solution-provided'
        days-before-stale: 90
        days-before-close: -1
