name: VMSS Test Only

on:
  push:
    branches: ['**']  # Runs on any branch
  workflow_dispatch:
    inputs:
      vmss_capacity:
        description: 'Number of VMSS instances to provision'
        required: false
        default: '3'

env:
  AZURE_RESOURCE_GROUP: dbatools-ci-runners
  VMSS_SUBSCRIPTION_ID: ${{ secrets.VMSS_AZURE_SUBSCRIPTION_ID }}
  VMSS_CUSTOM_IMAGE_ID: ${{ secrets.VMSS_AZURE_CUSTOM_IMAGE_ID }}

jobs:
  prepare-build:
    runs-on: ubuntu-latest
    outputs:
      build-id: ${{ steps.generate-id.outputs.build-id }}
      vmss-name: ${{ steps.generate-vmss-name.outputs.vmss-name }}
      vmss-capacity: ${{ steps.determine-capacity.outputs.capacity }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Generate build ID
      id: generate-id
      run: |
        BUILD_ID="${{ github.run_id }}-$(date +%s)"
        echo "build-id=$BUILD_ID" >> $GITHUB_OUTPUT

    - name: Generate VMSS name
      id: generate-vmss-name
      run: |
        sed -i 's/\r$//' .github/scripts/generate-vmss-name.sh
        chmod +x .github/scripts/generate-vmss-name.sh
        .github/scripts/generate-vmss-name.sh \
          "${{ github.actor }}" \
          "${{ github.event_name }}" \
          "${{ github.event_name == 'pull_request' && github.head_ref || github.ref_name }}"

    - name: Determine capacity
      id: determine-capacity
      run: |
        CAPACITY="${{ github.event.inputs.vmss_capacity || '3' }}"
        echo "capacity=$CAPACITY" >> $GITHUB_OUTPUT
        echo "VMSS capacity: $CAPACITY"

  provision-vmss:
    needs: prepare-build
    runs-on: ubuntu-latest
    outputs:
      runner-token: ${{ steps.get-token.outputs.runner-token }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.VMSS_AZURE_CREDENTIALS }}

    - name: Get GitHub runner registration token
      id: get-token
      run: |
        TOKEN=$(curl -X POST \
          -H "Authorization: token ${{ secrets.VMSS_GH_PAT }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/actions/runners/registration-token | jq -r .token)
        echo "::add-mask::$TOKEN"
        echo "runner-token=$TOKEN" >> $GITHUB_OUTPUT

    - name: Create or update VMSS
      run: |
        sed -i 's/\r$//' .github/scripts/create-vmss.sh
        chmod +x .github/scripts/create-vmss.sh
        .github/scripts/create-vmss.sh \
          "${{ needs.prepare-build.outputs.vmss-name }}" \
          "${{ needs.prepare-build.outputs.vmss-capacity }}" \
          "${{ env.AZURE_RESOURCE_GROUP }}" \
          "${{ env.VMSS_CUSTOM_IMAGE_ID }}" \
          "${{ github.actor }}" \
          "${{ github.event_name == 'pull_request' && github.head_ref || github.ref_name }}" \
          "${{ steps.get-token.outputs.runner-token }}" \
          "${{ github.repository }}" \
          "${{ needs.prepare-build.outputs.build-id }}"

    - name: Wait for VMSS instances to be ready
      run: |
        VMSS_NAME="${{ needs.prepare-build.outputs.vmss-name }}"
        echo "Waiting for VMSS instances to be in running state..."

        for i in {1..20}; do
          RUNNING_COUNT=$(az vmss list-instances \
            --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
            --name "$VMSS_NAME" \
            --query "[?instanceView.statuses[?code=='PowerState/running']] | length(@)" \
            --output tsv)

          echo "Running instances: $RUNNING_COUNT/${{ needs.prepare-build.outputs.vmss-capacity }}"

          if [ "$RUNNING_COUNT" -eq "${{ needs.prepare-build.outputs.vmss-capacity }}" ]; then
            echo "All instances are running"
            break
          fi

          if [ $i -eq 20 ]; then
            echo "Timeout waiting for instances to start"
            exit 1
          fi

          sleep 15
        done

    - name: Deploy set-registry script to VMSS instances
      run: |
        VMSS_NAME="${{ needs.prepare-build.outputs.vmss-name }}"
        TEMP_FILE="temp-set-registry-${VMSS_NAME}.ps1"

        # Read the template and replace placeholders
        cp .github/scripts/set-registry.ps1 "$TEMP_FILE"
        sed -i "s/--VMSS_GH_TOKEN--/${{ steps.get-token.outputs.runner-token }}/g" "$TEMP_FILE"
        sed -i "s/--GITHUB_REPOSITORY--/${{ github.repository }}/g" "$TEMP_FILE"
        sed -i "s/--BUILD_ID--/${{ needs.prepare-build.outputs.build-id }}/g" "$TEMP_FILE"
        sed -i "s/--VMSS_NAME--/${{ needs.prepare-build.outputs.vmss-name }}/g" "$TEMP_FILE"

        echo "Deploying set-registry.ps1 to VMSS instances..."

        # Create the script content as a variable and deploy it
        SCRIPT_CONTENT=$(cat "$TEMP_FILE" | base64 -w 0)

        az vmss run-command invoke \
          --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
          --name "$VMSS_NAME" \
          --command-id RunPowerShellScript \
          --scripts "
            New-Item -ItemType Directory -Path 'C:\scripts' -Force | Out-Null
            [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String('$SCRIPT_CONTENT')) | Set-Content -Path 'C:\scripts\set-registry.ps1' -Encoding UTF8
            Write-Host 'set-registry.ps1 deployed successfully' -ForegroundColor Green
          "

        # Clean up temp file
        rm "$TEMP_FILE"

        echo "set-registry.ps1 deployed to all VMSS instances for $VMSS_NAME"

  wait-for-runners:
    needs: [prepare-build, provision-vmss]
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - name: Wait for dedicated runners
      run: |
        VMSS_NAME="${{ needs.prepare-build.outputs.vmss-name }}"
        BUILD_ID="${{ needs.prepare-build.outputs.build-id }}"
        EXPECTED_RUNNERS="${{ needs.prepare-build.outputs.vmss-capacity }}"

        echo "Waiting for runners from VMSS: $VMSS_NAME"
        echo "Expected runners: $EXPECTED_RUNNERS"

        for i in {1..30}; do
          RUNNER_COUNT=$(curl -s -H "Authorization: token ${{ secrets.VMSS_GH_PAT }}" \
            "https://api.github.com/repos/${{ github.repository }}/actions/runners" | \
            jq "[.runners[] | select(.labels[].name | contains(\"$VMSS_NAME\"))] | length")

          echo "Registered runners: $RUNNER_COUNT/$EXPECTED_RUNNERS"

          if [ "$RUNNER_COUNT" -ge "$EXPECTED_RUNNERS" ]; then
            echo "All expected runners are available!"
            break
          fi

          if [ $i -eq 30 ]; then
            echo "Timeout: Not all runners came online"
            echo "Continuing with available runners..."
          fi

          sleep 20
        done

  # Simple test that runs on each VMSS instance
  test-connectivity:
    needs: [prepare-build, provision-vmss, wait-for-runners]
    runs-on: [self-hosted, "${{ needs.prepare-build.outputs.vmss-name }}"]
    timeout-minutes: 5
    strategy:
      matrix:
        test: [1, 2, 3] # This will create 3 jobs that can run on different instances
    steps:
    - name: Test VMSS connectivity
      run: |
        Write-Host "=== VMSS Test ===" -ForegroundColor Green
        Write-Host "Machine: $env:COMPUTERNAME" -ForegroundColor Yellow
        Write-Host "Test Job: ${{ matrix.test }}" -ForegroundColor Yellow
        Write-Host "VMSS Name: ${{ needs.prepare-build.outputs.vmss-name }}" -ForegroundColor Yellow
        Write-Host "Build ID: ${{ needs.prepare-build.outputs.build-id }}" -ForegroundColor Yellow

        # Simulate some work
        Write-Host "Simulating work for 60 seconds..." -ForegroundColor Cyan
        Start-Sleep -Seconds 60

        Write-Host "Test completed on $(Get-Date)" -ForegroundColor Green

  cleanup-vmss:
    needs: [prepare-build, provision-vmss, test-connectivity]
    if: always()
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.VMSS_AZURE_CREDENTIALS }}

    - name: Cleanup VMSS and runners
      run: |
        sed -i 's/\r$//' .github/scripts/cleanup-vmss.sh
        chmod +x .github/scripts/cleanup-vmss.sh
        .github/scripts/cleanup-vmss.sh \
          "${{ needs.prepare-build.outputs.vmss-name }}" \
          "${{ env.AZURE_RESOURCE_GROUP }}" \
          "${{ secrets.VMSS_GH_PAT }}" \
          "${{ github.repository }}" \
          "true"